.Dd 2020-10-05
.Dt REV 1
.Os rsUtils
.Sh NAME
.Nm rev
.Nd reverse each line
.Sh SYNOPSIS
.Nm
[\fI\,FILE1\/\fR]...
[\fI\,FILE2\/\fR]...
.Sh DESCRIPTION
.Nm
reads each
.Ar file
in sequence and writes it to stdout, but with all characters in each
line in reverse order.
If no
.Ar file
is given, or if
.Ar file
is "-"
.Nm
reads from stdin.
.Sh AUTHOR
Written by the JeanG3nie for rsUtils.
.Sh SEE ALSO
.Xr cat 1 ,
.Xr tac 1
