.Dd 2020-09-22
.Dt NPROC 1
.Os rsUtils
.Sh NAME
.Nm nproc
.Nd print the number of processing units available
.Sh SYNOPSIS
.Nm
.Op Fl ahV
.Sh DESCRIPTION
.Nm
Print the number of processing units available to the current process,
which may be less than the number of online processors
.Bl -tag -width Ds
.It Fl a, -all
print the number of installed processors
.It Fl h, -help
print a terse usage statement and exit.
.It Fl V, -version
display the program name and version and exit
.Sh AUTHOR
Written by the JeanG3nie for rsUtils.
.Sh SEE ALSO
.Xr get_nprocs 3
.Sh HISTORY
A
.Nm
utility first appeared in GNU coreutils.
