.Dd 2020-11-19
.Dt FACTOR 1
.Os rsUtils
.Sh NAME
.Nm factor
.Nd factor numbers
.Sh SYNOPSIS
.Nm
.Ar number 1
.Ar number 2
.Sh DESCRIPTION
Print the prime factors of each specified integer
.Ar NUMBER .
If none are specified on the command line, read them from standard input.
.Sh EXIT STATUS
.Ex -std factor
.Sh AUTHOR
Written by the JeanG3nie for rsUtils.
